### ISSUE TITLE
Compiling Java code?

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/housing-model#34]
@EconomicSL/core-devs What is the standard tool stack for building Java projects? Is [Maven](https://maven.apache.org/) the most widely used standard? What about [Gradle](https://gradle.org/), I have zero experience to draw from but I have an allergic reaction to XML and would prefer build scripts that are human readable.

Ideally all of our repos should be built using the same build tool which means the tool needs to be able to compile both Java and Scala. I am pretty sure that Maven and Gradle are capable of doing this...

**Comment by DavoudTaghawiNejad** [comment]
I use Maven for core Esl. Passes the human readability test.
