### ISSUE TITLE
Need to re-license the code to Apache 2.0

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/housing-model#35]
@rafabap we need to re-license this repo to use Apache 2.0 instead of MIT license for consistency sake.

**Comment by davidrpugh** [comment]
@adrian-carro This is going to be non-trivial or impossible. We need to look carefully at the license for each dependency of our project o make sure that they are compatible with Apache 2.0.  Many current dependencies look to be GPL'd.

**Comment by davidrpugh** [comment]
Here is a summary of the licenses of the dependencies (all of which we are distributing along with our source code which complicates matters)...

* Mason 0.18: [Academic Free License](https://en.wikipedia.org/wiki/Academic_Free_License) Compatible with Apache 2.0 license.
* JFreeChart: [Lesser General Public License](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) This is a Mason dependency required for some charting (including the GUI I think).  If we distribute this library with our source code then for sure we will need to license our source code as LGPL (which is not compatible with Apache 2.0).
* Java Media Framework: [Sun Community License](https://en.wikipedia.org/wiki/Sun_Community_Source_License) Not a widely used open source license; doesn't seem to be compatible with our needs.  Fortunately this is a Mason dependency that is used for generating movies and hopefully we can delete this .jar file from our source.  I am slightly concerned that  it might also be required to run the GUI (I will check).
* iText: [Affero General Public License](https://en.wikipedia.org/wiki/Affero_General_Public_License) This is another Mason dependency used to generate PDF files. This license is not compatible with LGPL and by distributing with GPL'D source code we are in violation of the license agreement.  Fortunately I do not think that we can delete this dependency.

Note that anything from Apache commons is fair game as all of the Apache Foundation software is licensed under the Apache 2.0 license.

**Comment by adrian-carro** [comment]
Closing this issue as no update for more than a year and this is not considered relevant any more for this piece of code.
