### ISSUE TITLE
Remove commented out code...

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/housing-model#41]
@adrian-carro I am noticing quite a bit of "dead code" that has been commented out but not deleted.  Can you please go through and delete this code? I would do it myself, but I worry that I may inadvertently delete something that you might really have needed.

**Comment by adrian-carro** [comment]
@davidrpugh Most of the dead code is not mine but previous (whether Dan's or Rafa's), but still, I'd prefer to go through it myself and with time, so as to make sure I'm not deleting anything that might come useful (even if just to understand the evolution of the code before deleting).

**Comment by davidrpugh** [comment]
@adrian-carro Yes, I recognize it as mostly Dan's.  Take your time.  Will leave this issue open as a reminder.

**Comment by adrian-carro** [comment]
I'm closing this issue as PR #44 and PR #45 have significantly reduced the amount of dead code. There is still way to go for a properly clean code, but they will be cleaned as they need to be modified, so I think it doesn't make sense to keep this issue. It can be brought up again in the future if need be.
